export { productName } from "../lib/product";
export const guaranteeLine = "If your refund hasn't landed 30 days after its due date and you followed the steps, you get the ₹49 back.";

export const metaCopy = {
  title: "Refund Genie: who owes your flight refund?",
  description: "Stuck domestic flight refund? See who owes you, the due date with its source, and your next message. You send every mail; Refund Genie follows the replies.",
};

export const landingCopy = {
  headerLink: "See a real case",
  eyebrow: "For event tickets bought in India",
  headline: "Stuck ticket refund? We'll stay on it till the money lands.",
  sub: "Paste what the organiser told you. In under a minute you'll know where your refund stands, the date it's due, and the exact message to send. Add the check-in to your calendar. If the money hasn't come by then, your next step is ready.",
  primary: "Start my case",
  secondary: "See a real case first",
  trust: "Free to check · No sign-up · Nothing is sent without you",
  example: {
    platform: "BookMyShow",
    label: "Example",
    event: "Monsoon Live, Bengaluru · 2 tickets",
    amount: "₹3,500",
    route: "On its way",
    due: "Due by 23 Oct 2026",
    source: "They said \"within 7-10 working days\" on 9 Oct 2026.",
    next: "Nothing to send yet. Your check-in: 24 Oct 2026.",
  },
  familiarTitle: "Sound familiar?",
  familiar: [
    "The match got moved to another city.",
    "Support said \"we don't know yet\". For four days.",
    "Then a form. Then a courier, at your cost. Then two weeks of silence.",
  ],
  familiarNote: "Based on a real case. ₹2,400. About 20 days.",
  howTitle: "How it works",
  how: [
    ["Paste the message.", "SMS, email, WhatsApp or a screenshot. Or just tell us what happened."],
    ["Know where you stand.", "Your refund route, the date it's due, and why that date."],
    ["Send the right message.", "Written for you. It opens in your own email, ready to send. Edit anything."],
    ["Check in on the date.", "It goes on your calendar with your case link. Not there yet? Your next step is ready."],
  ],
  whyTitle: "Why not just ask ChatGPT?",
  why: [
    ["It remembers your case.", "Every message, every date, every proof. One link."],
    ["It knows the route.", "Cancelled, postponed, moved, failed payment, \"refunded\" but missing. Each one has a different path."],
    ["It's ready when you come back.", "On your check-in date, the next step is already written."],
  ],
  neverTitle: "What we never do",
  never: [
    "Ask for OTPs, passwords, card numbers or bank logins.",
    "Send anything without you. Messages go from your own email.",
    "Keep your case after you delete it.",
  ],
  handleTitle: "What we handle",
  handles: ["Event cancelled", "Postponed", "Venue changed", "Money gone, no ticket", "\"Refunded\" but not received", "Can't attend (we'll tell you honestly)"],
  handleLine: "BookMyShow, District and organisers' own ticket sites. Concerts, comedy, cricket, festivals.",
  pricingTitle: "Pricing",
  freeTitle: "Free to check.",
  freeBody: "Your route, your date and your first step. Always free.",
  paidTitle: "₹49 to stay on it.",
  paidBody: "For refunds of ₹300 or more. Every message after the first, written for you: follow-ups, the grievance officer email, the helpline complaint.",
  under300: "Refunds under ₹300 are free, start to finish.",
  questionsTitle: "Questions",
  questions: [
    ["Do you contact the organiser for me?", "No. You send every message, from your own email or the app's chat. We write it and tell you where to send it. That keeps it real, and it keeps you in control."],
    ["How do you know the dates?", "From what the organiser promised, the platform's own refund policy, or the rules, like the RBI's rule for failed payments. Every date shows where it came from. When we have to estimate, we say so."],
    ["Is this legal advice?", "No. We help you use the routes that already exist: support, the platform's grievance officer, and the National Consumer Helpline."],
    ["Which platforms?", "BookMyShow, District, and organisers' own ticket sites in India. Flights are next."],
    ["My refund isn't for an event ticket.", "We're starting with event tickets. Tell us what it is and we'll let you know when we cover it."],
  ],
  privacyQuestion: "What happens to my data?",
  privacyPaid: "Your case lives at a private link only you have. We use Google's Gemini to read your messages and write drafts, on a paid plan where Google doesn't use them to improve its products. Delete your case and it's gone.",
  privacyFree: "Your case lives at a private link only you have. We use Google's Gemini to read your messages and write drafts. During testing we use Gemini's free tier, under which Google may use content to improve its products. Delete your case and it's gone.",
  footer: "Refund Genie helps you follow the refund routes that already exist. Not legal advice.",
  privacyLink: "Privacy",
  contactLink: "Contact",
};

// Flight positioning is separate so the existing event screens keep their copy.
export const annualGuaranteeLine = "If Refund Genie recovers nothing in that year, your Rs 49 comes back.";
export const flightLandingCopy = {
  ...landingCopy,
  headerLink:"Try a flight demo", eyebrow:"For stuck domestic flight refunds in India",
  headline:"Airline or travel site: who owes your refund?",
  sub:"Paste the cancellation mail. Refund Genie shows who owes you, the refund date with its source, and the next person to ask. You send the mail. When they reply, your next step updates.",
  primary:"Check my flight refund",secondary:"Try a flight demo",trust:"Free first check · No sign-up · You send every mail",
  example:{platform:"IndiGo · MakeMyTrip",label:"Made-up flight case",event:"Delhi → Mumbai · booked through MakeMyTrip",amount:"₹5,400",route:"Overdue",due:"Due about 25 Sep 2026",source:"Cancelled 7 Sep. DGCA: 14 working days; counting from cancellation is Refund Genie’s reading.",next:"Who owes you: IndiGo. Ask MakeMyTrip’s grievance officer, with IndiGo’s Nodal Officer in CC."},
  familiarTitle:"“We’re waiting for the airline.”",
  familiar:["The airline cancelled. The travel site says the refund is pending.","Then “refund processed”. Your bank still shows nothing.","Who has the money, and who do you ask next?"],
  familiarNote:"Patterns reported in public refund complaints. Each case needs its own evidence.",
  how:[
    ["Paste the cancellation mail.","Or add a screenshot. Confirm airline, booked via, cancellation date and PNR."],
    ["See who owes you.","The owner, date and rule line. Checked officer contacts, with their source page."],
    ["Send your next mail.","Open a draft in your own Gmail. Keep the case inbox in CC so a reply can update your case."],
    ["Come back on your date.","If it hasn’t landed, the next person and message are ready. You send and file every step."],
  ],
  whyTitle:"A refund chase that keeps its place.",
  why:[
    ["It keeps the dated record.","Your messages, replies and next check-in stay in one private case."],
    ["It follows the money.","A reply saying the airline paid the travel site changes the next person you ask."],
    ["The rule has a source.","Dates are worked out in code. Refund Genie’s own expectations are labelled."],
  ],
  handles:["Airline cancelled","You cancelled","Pending with airline","Processed, not received","Credit shell offered"],
  handleLine:"Domestic refunds with IndiGo, Air India, SpiceJet and Akasa Air; MakeMyTrip, Goibibo, Cleartrip and EaseMyTrip. For other companies you add the address from their own page. International flights and compensation claims are outside this version.",
  paidTitle:"Rs 49 a year.",paidBody:"Stay on every case for that year: replies, follow-ups, officer emails and complaint text. You send every message.",under300:"Cases Ganesh helps by hand this week are free. Demos never need payment.",
  questions:[
    ["Does Refund Genie send or log in for me?","No. You send every real mail, make every call and file every complaint. Refund Genie never logs in to an airline, travel site or bank for you."],
    ["Where do the dates come from?","DGCA refund rules, the company’s own message or policy, or a labelled Refund Genie expectation. Working days mean Monday to Friday; estimates ignore holidays."],
    ["What if the airline says it paid the travel site?","The airline stays answerable under the rule. The next mail asks the travel site for the bank reference and date it sent the refund to you, with the airline copied."],
    ["How does the demo work?","DemoTrips and Demo Air play two made-up roles. Send three demo mails from your own Gmail, watch replies update the case, then skip to the bank check date. No real booking or money."],
    ["Is this legal advice?","No. Refund Genie helps you use refund and grievance routes, with sources. It does not act as your lawyer or file for you."],
    ["What does Rs 49 cover?","A year of staying on every case. Your first check and first step are free. If Refund Genie recovers nothing in that year, the Rs 49 comes back. Ganesh checks payment claims by hand."],
  ],
};

export const sampleCopy = {
  banner: "This is a sample based on a real case. Nothing here is live.",
  start: "Start my own case",
  sendNote: "In your case, this opens your own email app.",
  timeline: "Timeline",
  showAll: "Show all",
  showLess: "Show less",
  message: "See the message we'd prepare",
  messageTitle: "Your message to support",
  messageBody: "Hello BookMyShow team,\n\nMy match was moved from Ahmedabad to Chennai. I chose the refund option and sent the physical tickets for scanning. Please confirm that you received them and tell me when my ₹2,400 refund will reach my original payment method. Please also share the refund reference number when it is processed.\n\nThank you.",
  close: "Close",
  status: "You need to act",
  event: "IPL match moved to another city",
  platform: "BookMyShow · 2 tickets",
  amount: "₹2,400",
  statusTitle: "A form and physical tickets were needed for this refund.",
  source: "Based on the organiser's instructions in the original case.",
  stepTitle: "Keep proof of each step",
  steps: ["Fill in the refund form.", "Photograph the tickets before sending them.", "Keep the courier receipt and tracking number.", "Screenshot the form after submitting it."],
  checkin: "The refund landed about 20 days after the venue change. This is a past case, not a promised date for yours.",
  saveTitle: "Your case stays at one private link",
  saveBody: "In your own case, you can add a check-in to your calendar and return through that link.",
};

export const intakeCopy = {
  title: "What did they tell you?",
  helper: "Paste the message from BookMyShow, District or the organiser. Or describe what happened in a line or two.",
  placeholder: "e.g. \"Your booking BKMY12345 for Monsoon Live on 18 Oct has been cancelled. Refund of Rs 3,500 in 7-10 working days.\"",
  paste: "Paste",
  screenshot: "Add screenshot",
  pasteRefused: "Long-press in the box and tap Paste.",
  chipsLabel: "Or start with what happened",
  chips: [
    ["Event cancelled", "My event was cancelled."],
    ["Postponed", "My event was postponed."],
    ["Venue changed", "The venue was changed."],
    ["Money gone, no ticket", "Money was debited but I didn't get a ticket."],
    ["\"Refunded\" but not received", "They say it's refunded but it's not in my account."],
    ["I can't go", "I can't attend and want my money back."],
  ],
  safety: "Don't include OTPs or card numbers. We remove them if you do. Crop them out of screenshots.",
  submit: "Check my refund",
  disabled: "Add a message, a screenshot or pick what happened.",
};

export const caseCopy = {
  badLink: "We can't open this case. Check you copied the whole link, including the part after the # sign.",
  progress: ["Reading your message", "Finding your refund route", "Working out your date", "Writing your next step"],
  working: "Still working. Your message is saved.",
  error: "Something went wrong on our side. Your case is safe.",
  retry: "Try again",
  needInfo: "Need a bit more",
  questionTitle: "A couple of quick questions",
  continue: "Continue",
  routeLabels: {
    WAIT: "On its way", OVERDUE: "Overdue", ACTION_NEEDED: "You need to act",
    TRACE: "Refunded, not received", FAILED_PAYMENT: "Payment failed",
    NO_ROUTE: "No refund route", NEED_INFO: "Need a bit more", OUT_OF_SCOPE: "Not tickets (yet)",
  },
  waitNext: "Nothing to send yet.",
  saveTitle: "Don't lose this case",
  calendar: "Add check-in to calendar",
  copyLink: "Copy my case link",
  share: "Send to myself",
  linkNote: "Anyone with this link can see this case, including your screenshots. Don't forward it.",
  copied: "Copied",
  addDate: "Your dates changed. Add the new check-in.",
  prepareEmail: "Prepare email",
  openEmail: "Open in Gmail",
  draftTitle: "Your message to support",
  emailHelp: "We couldn't confirm where to send this. Paste the organiser's message that names the channel, or find Contact us in the app's Help section.",
  emailNote: "Gmail opens in a browser tab. Nothing is sent until you press send there.",
  trackingOn: "Reply tracking is on for this case.",
  trackingOff: "Reply tracking is off until you mark your first message sent.",
  ccLabel: "Add this address in CC",
  liveAlertNeedsCalendar: "A live reply alert needs Google Calendar permission.",
  calendarFileOneTime: "A downloaded calendar file is a one-time reminder. It cannot alert you when a reply arrives.",
  calendarTitle: (amount: string, eventName: string) => `Check your ${amount}${amount === "refund" ? "" : " refund"} (${eventName})`,
  calendarDescription: (amount: string, eventName: string, caseLink: string) => `Has your ${amount}${amount === "refund" ? "" : " refund"} for ${eventName} landed? Open your case to update it or get your next step: ${caseLink}\n\nRefund Genie. Nothing is sent without you.`,
};

