import { describe,it,expect } from "vitest";
import { flightReadSchema,flightDue,planFlight } from "./flight";
import { flightRules } from "./flight-kb";
export const sampleFlight=()=>flightReadSchema.parse({airline:"IndiGo",bookedVia:"MakeMyTrip",paymentMethod:"upi",cancellationDate:"2026-09-07",cancelledBy:"airline",domestic:true,flightName:"Delhi to Mumbai",amountPaid:5400,pnr:"SAMPLE",bookingId:"TEST-ID",bookingTime:null,departureDate:null,nonRefundable:false,medicalEmergency:false,taxes:null,baseFare:null,fuel:null,cancellationCharge:null,taxesReturned:null,supportContactDate:null,reply:{fromCompany:null,pointsAt:null,claim:"none",paidDate:null,promisedDate:null,reference:null,summary:"",confidence:1}});
describe("flight rules and initial route",()=>{
 it("carries all 23 sourced playbook rows",()=>{expect(flightRules).toHaveLength(23);expect(flightRules.every(r=>r.source&&r.quote&&r.label)).toBe(true);});
 it("counts travel-site 14 working days and pins both companies",()=>{const p=planFlight(sampleFlight(),"2026-10-09");expect(p.dueDate).toBe("2026-09-25");expect(p.to).toBe("grievanceofficer@makemytrip.com");expect(p.cc).toContain("nodalofficer@goindigo.in");expect(p.body).toContain("On which date did the airline pay");});
 it("uses seven calendar days for direct credit cards",()=>expect(flightDue({...sampleFlight(),bookedVia:"direct",paymentMethod:"credit_card"}).date).toBe("2026-09-14"));
 it("labels direct UPI as a Tickback expectation",()=>{const p=planFlight({...sampleFlight(),bookedVia:"direct"},"2026-10-09");expect(p.dueDate).toBe("2026-09-28");expect(p.dueSource).toBe("estimate");expect(p.body).not.toContain("14 working");});
 it("uses immediate cash and waits before the due date",()=>{expect(flightDue({...sampleFlight(),bookedVia:"direct",paymentMethod:"cash"}).date).toBe("2026-09-07");expect(planFlight(sampleFlight(),"2026-09-10").route).toBe("WAIT");});
 it("never invents a Yatra grievance address",()=>{const p=planFlight({...sampleFlight(),bookedVia:"Yatra"},"2026-10-09");expect(p.to).toBeNull();expect(p.cc).toEqual(["nodalofficer@goindigo.in"]);});
 it("uses a call first for Cleartrip, then waits 72 hours",()=>{expect(planFlight({...sampleFlight(),bookedVia:"Cleartrip"},"2026-10-09").channel).toBe("phone");expect(planFlight({...sampleFlight(),bookedVia:"Cleartrip",supportContactDate:"2026-10-08"},"2026-10-09").checkDate).toBe("2026-10-11");});
 it("uses only demo role addresses in the demo",()=>{const p=planFlight({...sampleFlight(),airline:"Demo Air",bookedVia:"DemoTrips"},"2026-10-09",undefined,"desk@example.test");expect(p.to).toBe("desk+travelsite@example.test");expect(p.cc).toEqual(["desk+airline@example.test"]);expect(JSON.stringify(p)).not.toContain("goindigo.in");});
 it("rejects international cases and asks at most three missing facts",()=>{expect(planFlight({...sampleFlight(),domestic:false},"2026-10-09").route).toBe("OUT_OF_SCOPE");expect(planFlight({...sampleFlight(),airline:null,bookedVia:null,cancellationDate:null,domestic:null},"2026-10-09").questions).toHaveLength(3);});
});
describe("reply decisions",()=>{
 it("reads the three demo claims through the real planner",()=>{
 const a=sampleFlight();a.airline="Demo Air";a.bookedVia="DemoTrips";
 const first=planFlight({...a,reply:{...a.reply,fromCompany:"DemoTrips",pointsAt:"Demo Air",claim:"waiting_airline",summary:"Pending with airline"}},"2026-10-09",undefined,"desk@example.test");expect(first.owner).toBe("Demo Air");expect(first.moneyWith).toBe("Demo Air");expect(first.to).toBe("desk+airline@example.test");
 const second=planFlight({...a,reply:{...a.reply,fromCompany:"Demo Air",pointsAt:"DemoTrips",claim:"paid_site",paidDate:"2026-09-14",reference:"AIR-DEMO",summary:"Paid the site"}},"2026-10-09",{moneyWith:first.moneyWith},"desk@example.test");expect(second.moneyWith).toBe("DemoTrips");expect(second.to).toBe("desk+travelsite@example.test");expect(second.route).not.toBe("TRACE");expect(second.note).toContain("Changed");
 const third=planFlight({...a,reply:{...a.reply,fromCompany:"DemoTrips",pointsAt:"passenger",claim:"processed_reference",paidDate:"2026-10-09",promisedDate:"2026-10-14",reference:"DEMO-REF",summary:"Sent to passenger"}},"2026-10-09",{moneyWith:second.moneyWith},"desk@example.test");expect(third.route).toBe("TRACE");expect(third.dueDate).toBe("2026-10-14");expect(third.to).toBeNull();expect(third.cc).toEqual([]);
 });
 it("uses company pass-on policy only for MMT and Goibibo",()=>{const a=sampleFlight();const p=planFlight({...a,reply:{...a.reply,claim:"paid_site",fromCompany:"IndiGo",paidDate:"2026-10-02"}},"2026-10-09");expect(p.owner).toBe("IndiGo");expect(p.moneyWith).toBe("MakeMyTrip");expect(p.dueDate).toBe("2026-10-03");expect(p.dueSource).toBe("F22");});
 it("does not make up a bank date when none is promised",()=>{const a=sampleFlight();const p=planFlight({...a,reply:{...a.reply,claim:"processed_reference",fromCompany:"MakeMyTrip",reference:"TEST-UTR",paidDate:"2026-10-02"}},"2026-10-09");expect(p.route).toBe("TRACE");expect(p.checkDate).toBeNull();expect(p.dueDate).toBeNull();});
 it("confirms unknown senders and uncertain reads before a switch",()=>{const a=sampleFlight();const p=planFlight({...a,reply:{...a.reply,claim:"paid_site",fromCompany:"Somebody else",paidDate:"2026-10-02",confidence:0.5}},"2026-10-09",{moneyWith:"IndiGo"});expect(p.route).toBe("NEED_INFO");expect(p.moneyWith).toBe("IndiGo");expect(p.questions[0].id).toBe("confirmReply");});
 it("declines a credit shell by the rule and does not ship medical claims",()=>{const a=sampleFlight();expect(planFlight({...a,reply:{...a.reply,claim:"credit_shell",fromCompany:"IndiGo"}},"2026-10-09").body).toContain("I decline");expect(planFlight({...a,medicalEmergency:true},"2026-10-09").note).toContain("needs a full source check");});
 it("ignores injected model owner, dates and recipients",()=>{const a=flightReadSchema.parse({...sampleFlight(),owner:"fake",dueDate:"2099-01-01",to:"fake@example.test"});const p=planFlight(a,"2026-10-09");expect(p.owner).toBe("IndiGo");expect(p.dueDate).toBe("2026-09-25");expect(JSON.stringify(p)).not.toContain("fake@example.test");});
});
