from pathlib import Path
def edit(path,old,new):
 p=Path(path);s=p.read_text(encoding='utf-8');assert old in s,(path,old[:70]);p.write_text(s.replace(old,new),encoding='utf-8')
edit('convex/schema.ts','refundType: v.optional','deviceHash: v.optional(v.string()), handHelped: v.optional(v.boolean()), refundType: v.optional')
edit('convex/schema.ts',']).index("by_code", ["code"])',']).index("by_device", ["deviceHash"]).index("by_code", ["code"])')
edit('convex/schema.ts','  feedback: defineTable','  annualPasses: defineTable({deviceHash:v.string(),sourceCode:v.string(),startedAt:v.number(),expiresAt:v.number(),state:v.union(v.literal("claimed"),v.literal("confirmed"),v.literal("not_found")),graceUntil:v.optional(v.number())}).index("by_device",["deviceHash"]).index("by_source",["sourceCode"]),\n  feedback: defineTable')
edit('convex/cases.ts','assertAccess, findCase','assertAccess, findCase, hashToken')
edit('convex/cases.ts','import { demoSubject }','import { annualActive,razorpayPaymentLink } from "../lib/annual-pass";\nimport { demoSubject }')
edit('convex/cases.ts','code, tokenHash: args.tokenHash, stage:', 'code, deviceHash: await hashToken(args.deviceId), tokenHash: args.tokenHash, stage:')
edit('convex/cases.ts','const latestTrackedReply =', 'const annual = item.refundType === "flight" && item.deviceHash ? await ctx.db.query("annualPasses").withIndex("by_device",q=>q.eq("deviceHash",item.deviceHash!)).unique() : null;\n    const latestTrackedReply =')
edit('convex/cases.ts','code: item.code, refundType:', 'code: item.code, annualPaid: annualActive(annual,Date.now()), annualUntil:annual?.expiresAt??null, annualState:annual?.state??null, handHelped:item.handHelped??false, razorpayLink:item.refundType==="flight"?razorpayPaymentLink(process.env.NEXT_PUBLIC_RAZORPAY_PAYMENT_LINK):null, refundType:')
edit('convex/cases.ts','const locked = !!process.env.NEXT_PUBLIC_UPI_VPA','const annual=item.refundType==="flight"&&item.deviceHash?await ctx.db.query("annualPasses").withIndex("by_device",q=>q.eq("deviceHash",item.deviceHash!)).unique():null;\n    const flightLocked=item.refundType==="flight"&&!item.demo&&!item.handHelped&&!!razorpayPaymentLink(process.env.NEXT_PUBLIC_RAZORPAY_PAYMENT_LINK)&&!annualActive(annual,Date.now())&&rows.some(r=>r.status==="sent");\n    const locked = item.refundType==="flight"?flightLocked:!!process.env.NEXT_PUBLIC_UPI_VPA')
# Manual help is free for this week; only the internal admin operation can set this.
edit('convex/flights.ts','export const workCount=', 'export const handHelped=internalMutation({args:{code:v.string()},returns:v.null(),handler:async(ctx,{code})=>{const item=await ctx.db.query("cases").withIndex("by_code",q=>q.eq("code",code)).unique();if(item?.refundType==="flight")await ctx.db.patch(item._id,{handHelped:true});return null;}});\nexport const workCount=')
edit('app/c/flight-case-view.tsx','import { redact }','import { annualGuarantee } from "../../lib/annual-pass";\nimport { redact }')
edit('app/c/flight-case-view.tsx','const counts=','const claimAnnual=useMutation(api.annualPayments.claim),restoreAnnual=useMutation(api.annualPayments.restore);\n const counts=')
edit('app/c/flight-case-view.tsx','{data.factsConfirmedAt&&draft&&draft.status', '''{!data.demo&&!data.handHelped&&data.factsConfirmedAt&&!data.stage.startsWith("CLOSED")&&<section className="case-card price-card" aria-label="Annual payment"><h2>{data.annualPaid?"Your year is covered":"Rs 49 a year"}</h2>{data.annualPaid?<><p>Every case through {date(new Date(data.annualUntil!).toISOString().slice(0,10))}.</p><button className="text-button" disabled={busy} onClick={()=>run(()=>restoreAnnual({...args,deviceId:getDeviceId()}))}>Use my year on this device</button></>:<><p>{annualGuarantee}</p><p>Checking, your date and first step are free. Stay on every case for the year: replies, follow-ups and escalation steps. Ganesh checks payments daily.</p>{data.razorpayLink?<><a className="button button-primary" href={data.razorpayLink} target="_blank" rel="noreferrer">Pay Rs 49 for a year</a><p>Add {code} in the payment note.</p><button className="text-button" disabled={busy} onClick={()=>run(()=>claimAnnual({...args,deviceId:getDeviceId()}))}>I've paid</button></>:<><button className="button button-primary" disabled>Pay Rs 49 for a year</button><p>The payment link is being set up. Your first step is free.</p></>}</>}</section>}
 {data.factsConfirmedAt&&draft&&draft.body===null&&<section className="case-card"><h2>Your next message is ready</h2><p>The annual plan unlocks follow-ups. Your route and date remain visible.</p></section>}
 {data.factsConfirmedAt&&draft&&draft.body!==null&&draft.status''')
edit('app/page.tsx','guaranteeLine, landingCopy','annualGuaranteeLine, flightLandingCopy')
edit('app/page.tsx','{guaranteeLine}','{annualGuaranteeLine}')
edit('app/page.tsx','href="/sample">{c.secondary}','href="/start">{c.secondary}')
edit('app/page.tsx','BUILT FOR TICKET REFUNDS','BUILT FOR DOMESTIC FLIGHT REFUNDS')
edit('app/privacy/page.tsx','optional name, booking ID','optional name, PNR, booking ID')
edit('app/privacy/page.tsx','<section><h2>Keep sensitive details out</h2>', '<section><h2>Tickback never logs in</h2><p>You send every real message from your own account. Tickback never logs in to an airline, travel site, bank or payment account for you. We never ask for OTPs, passwords, card numbers or bank details.</p></section><section><h2>Annual payment</h2><p>Razorpay handles payment through its payment link. We keep the case code, amount, claimed payment date and yearly coverage status so Ganesh can reconcile it. A hashed device key links your cases to that year without a new account. Opening an existing covered private case lets you restore coverage on another device. If no case reaches It’s in during that year, the Rs 49 comes back. Demo cases and cases helped by Ganesh this week are free.</p></section>\n      <section><h2>Keep sensitive details out</h2>')
edit('app/privacy/page.tsx','<h2>Gmail reply tracking (optional)</h2><p>','<h2>Gmail reply tracking (optional)</h2><p>Gmail connect is open to test accounts only for now. Copying the case inbox works without connecting your Gmail.</p><p>')
edit('app/start/page.tsx','{c.chips.map(', '{(refundType==="flight"?[["Airline cancelled","The airline cancelled my domestic flight."],["I cancelled","I cancelled my domestic flight."],["Refund missing","The refund has not arrived."],["Pending with airline","The travel site says it is pending with the airline."]]:c.chips).map(')
edit('app/start/page.tsx','placeholder={c.placeholder}', 'placeholder={refundType==="flight"?"Paste your flight cancellation mail or the travel site’s reply…":c.placeholder}')
edit('app/start/page.tsx','{demoPicker && error &&', '{(demoPicker||refundType==="flight") && error &&')
